- project:
    bucardo-unitest:
      jobs:
        - bucardo-unitest-on-X86-perl5.30-PG10:
            irrelevant-files:
              - ^.*\.md$
              - ^.gitignore$
              - ^.*\.sh$
              - ^INSTALL$
              - ^LICENSE$
              - ^README.*$
              - ^SIGNATURE$
              - ^TODO$
              - ^UPGRADE$
